In [1]:
import pandas as pd
import numpy as np

from pyspark.sql import SparkSession
from pyspark.ml.tuning import CrossValidator, ParamGridBuilder
from pyspark.ml.classification import NaiveBayes
from pyspark.ml.stat import Correlation
from pyspark.ml.evaluation import MulticlassClassificationEvaluator
from pyspark.sql.functions import col

spark = SparkSession.builder \
    .master("local") \
    .appName("NaiveBayes") \
    .getOrCreate()

In [2]:
# load the dataset
data = spark.read.csv("GROUP2.csv.gz", header=True, sep=',',inferSchema="true")
#renaming winPlaceClass with label
data = data.withColumn("winPlaceClass", col("winPlaceClass") -1)
data = data.withColumnRenamed('winPlaceClass', 'label')
data.dtypes

[('groupId', 'string'),
 ('matchId', 'string'),
 ('matchDuration', 'int'),
 ('label', 'int'),
 ('isFirstPerson', 'boolean'),
 ('matchtype', 'int'),
 ('maxPlace', 'int'),
 ('numGroups', 'int'),
 ('hasDisconnected', 'int'),
 ('assist_SUM', 'int'),
 ('assist_MAX', 'int'),
 ('assist_AVG', 'int'),
 ('heals_SUM', 'int'),
 ('heals_MAX', 'int'),
 ('heals_AVG', 'int'),
 ('kills_SUM', 'int'),
 ('kills_MAX', 'int'),
 ('kills_AVG', 'int'),
 ('headshotKills_SUM', 'int'),
 ('headshotKills_MAX', 'int'),
 ('headshotKills_AVG', 'int'),
 ('killStreaks_MAX', 'int'),
 ('roadKills_SUM', 'int'),
 ('roadKills_MAX', 'int'),
 ('roadKills_AVG', 'int'),
 ('longestKill_MAX', 'double'),
 ('vehicleDestroys_MAX', 'int'),
 ('weaponsAcquired_SUM', 'int'),
 ('weaponsAcquired_MAX', 'int'),
 ('weaponsAcquired_AVG', 'int'),
 ('damageDealt_SUM', 'double'),
 ('damageDealt_MAX', 'double'),
 ('damageDealt_AVG', 'double'),
 ('distance_SUM', 'double'),
 ('distance_MAX', 'double'),
 ('distance_AVG', 'double'),
 ('rideDistance_SU

In [3]:
inputCols =  data.columns

toRemove = ['matchId', 'groupId', 'killPlace_MAX', 'rankPoints_MAX', 'killPoints_MAX', 'winPoints_MAX', 'label']
inputCols = list(set(inputCols) - set(toRemove))

In [4]:
from pyspark.ml.linalg import Vectors
from pyspark.ml.feature import VectorAssembler

assembler = VectorAssembler(
    inputCols=inputCols,
    outputCol="features")

output = assembler.transform(data)

## Feature Selection (correlation) 

In [5]:
pearsonCorr = Correlation.corr(output, 'features', 'pearson').collect()[0][0]
pearsonCorr

DenseMatrix(51, 51, [1.0, 0.3992, -0.2968, 0.4574, 0.4153, 0.4189, 0.3961, 0.3112, ..., 0.0677, 0.9348, 0.0047, 0.0101, 0.152, 0.0438, 0.1656, 1.0], False)

In [6]:
corr_matrix = pd.DataFrame(pearsonCorr.toArray(), inputCols, inputCols)
corr_matrix

heals_SUM  weaponsAcquired_MAX  maxPlace  DBNOs_MAX  \
heals_SUM             1.000000             0.399182 -0.296815   0.457439   
weaponsAcquired_MAX   0.399182             1.000000 -0.267301   0.331610   
maxPlace             -0.296815            -0.267301  1.000000  -0.550834   
DBNOs_MAX             0.457439             0.331610 -0.550834   1.000000   
assist_MAX            0.415324             0.306735 -0.340582   0.571159   
kills_MAX             0.418850             0.365927 -0.221101   0.707322   
longestKill_MAX       0.396104             0.369079 -0.198065   0.477852   
revives_AVG           0.311227             0.146669 -0.140615   0.282188   
kills_AVG             0.271560             0.278281  0.056869   0.407448   
weaponsAcquired_AVG   0.281917             0.844288 -0.034376   0.158517   
damageDealt_AVG       0.349300             0.340840 -0.084426   0.530731   
killStreaks_MAX       0.368229             0.340088 -0.323517   0.644243   
weaponsAcquired_SUM   0.507021             0.762004 -0.561053   0.527397   
assist_SUM            0.434344             0.302686 -0.325626   0.578636   
walkDistance_AVG      0.456811             0.593289 -0.143652   0.294908   
hasDisconnected      -0.000180            -0.037546 -0.190513   0.086226   
assist_AVG            0.251572             0.189031 -0.095198   0.343222   
distance_SUM          0.591312             0.536864 -0.359852   0.414515   
teamKills_AVG        -0.008819             0.005036  0.022231  -0.010323   
roadKills_AVG         0.001584             0.013660  0.034543  -0.012792   
revives_SUM           0.553800             0.300458 -0.352906   0.513657   
vehicleDestroys_MAX   0.138561             0.114530 -0.074648   0.119398   
heals_AVG             0.831590             0.321358 -0.071882   0.247645   
teamKills_SUM         0.100058             0.073458 -0.128529   0.117502   
DBNOs_SUM             0.499165             0.338607 -0.526748   0.924757   
matchtype             0.313793             0.262762 -0.907498   0.544868   
roadKills_SUM         0.050003             0.043725 -0.014166   0.045374   
rideDistance_AVG      0.311043             0.308966 -0.072952   0.109088   
swimDistance_SUM      0.120732             0.105711 -0.066064   0.061226   
isFirstPerson        -0.013397            -0.056457  0.019070  -0.008178   
damageDealt_MAX       0.447319             0.388742 -0.282439   0.748322   
rideDistance_SUM      0.415415             0.332984 -0.198033   0.212367   
distance_MAX          0.486093             0.545382 -0.178219   0.279209   
revives_MAX           0.518881             0.302433 -0.369687   0.509327   
headshotKills_SUM     0.347592             0.278156 -0.204432   0.560860   
numGroups            -0.296368            -0.269172  0.998446  -0.549239   
kills_SUM             0.495564             0.384814 -0.307399   0.767790   
damageDealt_SUM       0.535639             0.411897 -0.404409   0.814341   
walkDistance_MAX      0.488958             0.605741 -0.206687   0.351047   
heals_MAX             0.929366             0.392444 -0.244853   0.396762   
headshotKills_AVG     0.093955             0.131736  0.132230   0.148065   
DBNOs_AVG             0.380362             0.272987 -0.378047   0.833345   
teamKills_MAX         0.094602             0.072497 -0.128474   0.117925   
rideDistance_MAX      0.347030             0.332247 -0.120615   0.149221   
swimDistance_AVG      0.070174             0.080258 -0.000373   0.008848   
matchDuration         0.106431             0.170362  0.040627  -0.024082   
roadKills_MAX         0.048749             0.043483 -0.013165   0.044246   
distance_AVG          0.460835             0.532899 -0.127474   0.233786   
headshotKills_MAX     0.308784             0.267466 -0.172620   0.516546   
walkDistance_SUM      0.584716             0.580772 -0.417748   0.499249   
swimDistance_MAX      0.100414             0.099652 -0.041709   0.043349   

                     assist_MAX  kills_MAX  longestKill_MAX  revives

In [7]:
# Seleziono il triangolo superiore della correlation matrix
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))

# Cerco le features con correlazione > 0.9
to_drop = [column for column in upper.columns if any(upper[column] > 0.9)]

In [8]:
to_drop

['damageDealt_AVG',
 'assist_SUM',
 'DBNOs_SUM',
 'damageDealt_MAX',
 'revives_MAX',
 'numGroups',
 'kills_SUM',
 'damageDealt_SUM',
 'walkDistance_MAX',
 'heals_MAX',
 'teamKills_MAX',
 'rideDistance_MAX',
 'roadKills_MAX',
 'distance_AVG',
 'headshotKills_MAX',
 'swimDistance_MAX']

In [9]:
naiveBayesFeat = [col for col in inputCols if col not in to_drop]
naiveBayesFeat

['heals_SUM',
 'weaponsAcquired_MAX',
 'maxPlace',
 'DBNOs_MAX',
 'assist_MAX',
 'kills_MAX',
 'longestKill_MAX',
 'revives_AVG',
 'kills_AVG',
 'weaponsAcquired_AVG',
 'killStreaks_MAX',
 'weaponsAcquired_SUM',
 'walkDistance_AVG',
 'hasDisconnected',
 'assist_AVG',
 'distance_SUM',
 'teamKills_AVG',
 'roadKills_AVG',
 'revives_SUM',
 'vehicleDestroys_MAX',
 'heals_AVG',
 'teamKills_SUM',
 'matchtype',
 'roadKills_SUM',
 'rideDistance_AVG',
 'swimDistance_SUM',
 'isFirstPerson',
 'rideDistance_SUM',
 'distance_MAX',
 'headshotKills_SUM',
 'headshotKills_AVG',
 'DBNOs_AVG',
 'swimDistance_AVG',
 'matchDuration',
 'walkDistance_SUM']

In [10]:
assembler = VectorAssembler(
    inputCols=naiveBayesFeat,
    outputCol="features")

output = assembler.transform(data)

In [11]:
seed = 42
withReplacement=False
output = output.sample(withReplacement, 0.5, seed).select("features", "label")

(training,testing) = output.randomSplit([0.7,0.3])
print(F'training: {training.count()}')
print(F'testing: {testing.count()}')

training: 705702
testing: 302825


In [12]:
training.groupBy('label').count().toPandas()

label   count
0      1  165125
1      3  173846
2      5   16566
3      4  167917
4      2  165594
5      0   16654

## Grid Search

paramGrid = ParamGridBuilder() .addGrid(nb.smoothing, [0.0, 1.0, 5.0])  \
    .addGrid(nb.modelType, ['multinomial', 'gaussian']) \
    .build()

In [13]:
nb = NaiveBayes()

paramGrid = ParamGridBuilder() .addGrid(nb.smoothing, [0.0, 0.001, 0.01, 1.0])  \
    .addGrid(nb.modelType, ['multinomial', 'gaussian']) \
    .build()

crossval = CrossValidator(estimator=nb,
                          estimatorParamMaps=paramGrid,
                          evaluator=MulticlassClassificationEvaluator(),
                          numFolds=3) 

cvModel = crossval.fit(training)

In [14]:
# Best parameters
print(cvModel.getEstimatorParamMaps()[np.argmax(cvModel.avgMetrics)])

{Param(parent='NaiveBayes_c9293d015e27', name='smoothing', doc='The smoothing parameter, should be >= 0, default is 1.0'): 0.0, Param(parent='NaiveBayes_c9293d015e27', name='modelType', doc='The model type which is a string (case-sensitive). Supported options: multinomial (default), bernoulli and gaussian.'): 'gaussian'}


In [15]:
model = cvModel.bestModel

In [16]:
predictions = model.transform(testing)

## Evaluation

In [17]:
from pyspark.mllib.evaluation import MulticlassMetrics

predictionAndLabels = predictions.rdd.map(lambda x: (x.prediction, float(x.label)))
metrics = MulticlassMetrics(predictionAndLabels)

In [18]:
# Summary stats
print("Recall = %s" % metrics.weightedRecall)
print("Precision = %s" % metrics.weightedPrecision)
print("F1 measure = %s" % metrics.weightedFMeasure())
print("Accuracy = %s" % metrics.accuracy)

# Individual label stats
labels = [0.0, 1.0 ,2.0, 3.0, 4.0, 5.0]
for label in labels:
    print("Class %s precision = %s" % (label, metrics.precision(label)))
    print("Class %s recall = %s" % (label, metrics.recall(label)))
    print("Class %s F1 Measure = %s" % (label, metrics.fMeasure(label)))
    
print('Confusion Matrix')
print(metrics.confusionMatrix().toArray())

Recall = 0.34312556757203005
Precision = 0.4219803589184543
F1 measure = 0.36268647378873375
Accuracy = 0.34312556757203005
Class 0.0 precision = 0.23067031023951134
Class 0.0 recall = 0.6210328909405655
Class 0.0 F1 Measure = 0.33639382691932024
Class 1.0 precision = 0.6369647954329211
Class 1.0 recall = 0.37718680451869174
Class 1.0 F1 Measure = 0.47380434205637245
Class 2.0 precision = 0.4075125531093086
Class 2.0 recall = 0.2989021885402649
Class 2.0 F1 Measure = 0.3448580183861083
Class 3.0 precision = 0.33896864374763885
Class 3.0 recall = 0.2874687954718392
Class 3.0 F1 Measure = 0.3111018008191452
Class 4.0 precision = 0.3603967893381796
Class 4.0 recall = 0.3290787399397074
Class 4.0 F1 Measure = 0.34402648470479386
Class 5.0 precision = 0.10515925243485127
Class 5.0 recall = 0.9026973591300663
Class 5.0 F1 Measure = 0.18837397774994474
Confusion Matrix
[[4.3050e+03 2.1660e+03 3.6700e+02 5.8000e+01 1.0000e+00 3.5000e+01]
 [1.0891e+04 2.6778e+04 2.2586e+04 1.0221e+04 4.8400e+02

In [19]:
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

# obtain evaluator.
evaluator = MulticlassClassificationEvaluator(metricName="accuracy")

# compute the classification error on test data.
accuracy = evaluator.evaluate(predictions)
print("Accuracy = %g" % (accuracy))

Accuracy = 0.343126


## Sklearn Evalutation

In [20]:
from sklearn.metrics import classification_report, confusion_matrix

In [21]:
y_true = predictions.select(['label']).collect()
y_pred = predictions.select(['prediction']).collect()

In [22]:
print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.23      0.62      0.34      6932
           1       0.64      0.38      0.47     70994
           2       0.41      0.30      0.34     70595
           3       0.34      0.29      0.31     74909
           4       0.36      0.33      0.34     72314
           5       0.11      0.90      0.19      7081

    accuracy                           0.34    302825
   macro avg       0.35      0.47      0.33    302825
weighted avg       0.42      0.34      0.36    302825



In [23]:
print(confusion_matrix(y_true, y_pred))

[[ 4305  2166   367    58     1    35]
 [10891 26778 22586 10221   484    34]
 [ 2942 10857 21101 26688  8427   580]
 [  464  2089  7025 21534 32738 11059]
 [   53   150   695  4935 23797 42684]
 [    8     0     6    92   583  6392]]


In [25]:
spark.stop()